---

type: image
test_batch_size: 16
lr: 0.05
momentum: 0.9
decay: 0.0005
batch_size: 16

no_models: 100
epochs: 205
retrain_no_times: 2
divide_q: 0.55

base_model: office10_simpleCNN
#base_model: swin-t-cifar10

number_of_total_participants: 100
sampling_dirichlet: false
dirichlet_alpha: 0.2
eta: 5

save_model: ture
save_on_epochs: [100, 200, 300,400,500]
#resumed_model: model_cifar10_0.55_May.30_00.23.02/Target0_ResNet_18.pt.tar.epoch_2000
resumed_model:


environment_name: office10
report_train_loss: false
report_test_loss: false
report_poison_loss: false
track_distance: false
track_clusters: false
log_interval: 10

#modify_poison: true
modify_poison: false

# file names of the images
poison_type: wall

# manually chosen images for tests
poison_images_test:
#  - 330
#  - 568
#  - 3934
#  - 12336
#  - 30560

poison_images:
#  - 30696
#  - 33105
#  - 33615
#  - 33907
#  - 36848
#  - 40713
#  - 41706


#  image_29911.jpg
poison_image_id: 2775
poison_image_id_2: 1605
poison_label_swap: 2
size_of_secret_dataset: 200
poisoning_per_batch: 1
poison_test_repeat: 1000
is_poison: false
baseline: false
random_compromise: false
noise_level: 0.01


poison_epochs: [100000]
retrain_poison: 15
scale_weights: 100
poison_lr: 0.05
poison_momentum: 0.9
poison_decay: 0.005
poison_step_lr: false
clamp_value: 1.0
alpha_loss: 1.0
number_of_adversaries: 1
poisoned_number: 2
results_json: false

s_norm: 1000000
diff_privacy: false


fake_participants_load: false
fake_participants_file: data/reddit/updates_cifar.pt.tar
fake_participants_save: false

